# Generated by Django 4.0.3 on 2022-03-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='default_shipping_address',
        ),
    ]
