version: '2'
services:
  # db:
  #   image: mysql
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: mypassword
  #     MYSQL_USER: gbg
  #     MYSQL_PASSWORD: mypassword
  #     MYSQL_DATABASE: gbg_local
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    stdin_open: true # Add this line into your service
    tty: true # Add this line into your service
