# Generated by Django 4.0.3 on 2022-03-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='is_send',
            field=models.BooleanField(default=False),
        ),
    ]
