# Generated by Django 4.0.3 on 2022-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_amt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_click',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
